before:
  hooks:
  - go mod download

builds:

  - id: "teritorid-linux"
    main: ./cmd/teritorid
    binary: bin/teritorid
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=teritori -X github.com/cosmos/cosmos-sdk/version.AppName=evmosd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

 - id: "teritorid-linux-arm64"
    main: ./cmd/teritorid
    binary: bin/teritorid
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=teritori -X github.com/cosmos/cosmos-sdk/version.AppName=evmosd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
  format_overrides:
    - goos: windows
      format: zip
  builds:
  - teritorid-linux
  - teritorid-linux-arm64

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
snapshot:
  name_template: "{{ .Tag }}-next"
